name: flutter_learning
description: 'A new Flutter project.'
publish_to: 'none' # Remove this line if you wish to publish
version: 1.0.0+1

environment:
    sdk: ^3.5.4

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.8
    google_fonts: ^6.2.1
    go_router: ^14.6.1
    dio: ^5.7.0
    shared_preferences: ^2.3.3
    bloc: ^8.1.4
    flutter_bloc: ^8.1.6
    http: ^1.2.2
    hugeicons: ^0.0.7

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/images/
